[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval --benchmark-res pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 0 pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 1 pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 2 pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 3 pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --disable-peval pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 0 pendulum.dae"
options = "230763"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 1 pendulum.dae"
options = "9737"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 2 pendulum.dae"
options = "9737"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 3 pendulum.dae"
options = "9737"

[[post]]
runtime = "id"
