timing="complete"

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align --no-print-samples lda.mc"
options = "1000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align --no-print-samples lda.mc"
options = "10000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align --no-print-samples lda.mc"
options = "100000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --no-print-samples lda.mc"
options = "1000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --no-print-samples lda.mc"
options = "10000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --no-print-samples lda.mc"
options = "100000"

[[post]]
runtime = "id"
