timing="complete"

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align lda-res.mc"
options = "30000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align lda-res.mc"
options = "300000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight --align lda-res.mc"
options = "3000000"

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight lda-res.mc"
options = "30000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight lda-res.mc"
options = "300000"
[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-mcmc-lightweight lda-res.mc"
options = "3000000"

[[post]]
runtime = "Python3"
argument = "post.py"
options = ""
